### ISSUE TITLE
Flexbile Tool deletes NBT data when breaking block and sometimes even dupes it

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/Tools#11]
Flexible Tools 1.2.4
MC 1.12.1
Forge 2446

When breaking any block with a Flexible Tool, the dropped block loses all NBT data. For example you can test this with the RFTools Modular Storage. When you break it with items in it, it drops the block, but all NBT data is reset.

Even worse, if you test this with putting items in a Shulker Box and breaking it, then two Shulker Boxes drop and one of them lost the NBT data.

**Comment by KidsDontPlay** [comment]
the modular storage loses the nbt data because mcjty uses a deprecated method. But I fixed it in the next limelib version.
the shulker box is complicated. it uses a weird way to drop the box. I tried to break the box with AA Auto-Breaker and RFTools Quarry, it drops twice too.

**Comment by davqvist** [comment]
Just to make sure, it's not just the Modular Storage, basically everything that I broke with NBT data lost it, like Thermal Expansion stuff, YABBA Barrels and much more. Should I make more testing?

**Comment by KidsDontPlay** [comment]
No, I guess it's fixed
