### ISSUE TITLE
When there is lag, the Range Upgrade on the Pickaxe breaks in wrong direction

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/Tools#13]
MC 1.12
Forge 2443
FT 1.2.3

Server hasn't updated yet, I will test again on newer versions if needed.
Anyway, it's hard to describe and I don't know the exact causes, but it seems like whenever there is lag on the server and the block you break (with a Range increased pickaxe) doesn't drop immediately there is a chance that the block is broken not from the direction you were breaking, resulting in impossible breaking patterns. As I said it's both hard to recreate and hard to describe. I noticed in my stream, I couldn't find the part where I tested it intensively, but I found a few occassions where it happened as it happened quite regularly as we had issues with the server.

https://www.twitch.tv/videos/163908437 at 4:13:58 and 4:16:23
If you need more info, I will try to find the longer period where I tried to figure out when it happens.

**Comment by KidsDontPlay** [comment]
Due to the lag at the moment the block was destroyed you looked on a different side of another block. that's why the pattern was wrong. I'm gonna at a check whether the actual block and the block you are looking at are the same.
