### ISSUE TITLE
Flexible tools dupe and delete

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/Tools#20]
FT 1.2.6
Forge 2561
MC 1.12.2

Breaking any multiblock from Embers with a Flexible Pickaxe deletes the block, like the Mixer Centrifuge for example, assuming because it occupies 2 blocks.
Breaking an Item Barrel (Yabba) with a Flexible Axe dupes the block.

As it works with tools from other mods fine, I assume the issue is in your mod.

**Comment by KidsDontPlay** [comment]
Some mods use unusual methods to drop blocks. I tested with rftools builder and actually additions block breaker to break the blocks you mentioned and the problem remains.
I will add a config option to break tile entities the normal way with my tools

**Comment by davqvist** [comment]
Nice.
Forgive me my stupid question: Why does the tools not break all blocks the "normal" way?

**Comment by KidsDontPlay** [comment]
I need to know what the block will drop before it drops e.g. with the receiver upgrade.

**Comment by davqvist** [comment]
Thanks for clarfication

**Comment by MrRiegel** [comment]
Some mods use unusual methods to drop blocks. I tested with rftools builder and actually additions block breaker to break the blocks you mentioned and the problem remains.
I will add a config option to break tile entities the normal way with my tools
