### ISSUE TITLE
Crash on server "java.lang.NoClassDefFoundError: mcjty/theoneprobe/api/ProbeMode"

### ISSUE THREAD

**Issue by darkphan** [KidsDontPlay/Tools#22]
Version: 1.2.8
Crash log: https://pste.me/#/STDAJ

Not certain of the conditions that caused this crash, but we are not using the one probe in our modpack.

The player has an axpickvel with the following upgrades: vein, receiver, energy, 2x haste, silk touch.

**Comment by KidsDontPlay** [comment]
what block was he trying to mine?

**Comment by darkphan** [comment]
I believe it was an ore block from the OresAllEasy mod

**Comment by KidsDontPlay** [comment]
It's up to the author of OresAllEasy to fix that.
