### ISSUE TITLE
crash when mining a buildcraft laser

### ISSUE THREAD

**Issue by Delerium** [KidsDontPlay/Tools#26]
Mining a buildcraft laser crashes the game.

[crash-2018-06-07_06.31.02-client.txt](https://github.com/MrRiegel/Tools/files/2080238/crash-2018-06-07_06.31.02-client.txt)

**Comment by KidsDontPlay** [comment]
why do you post it here? open an issue in buildcraft's repository

**Comment by Delerium** [comment]
sorry, I was using a flexible tools pick and thought I saw flexible tools listed in the crash report. at a second glance I realize I was wrong.  I'll report to buildcraft, thanks.
