### ISSUE TITLE
Problem with Simply Jetpacks

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/Tools#33]
If you have a Simply Jetpacks Flux-Infused Jetplate on, it comes with the ability to charge your items in your inventory. Even with no Energy Upgrade on a Flexible Pickaxe for example the tool's progress while mining gets reset all the time. If you have the Energy Upgrade on the tool it works fine. It seems that the Jetplate tries to charge it while mining and fails and resets the mining progress. Not sure if related to https://github.com/MrRiegel/Tools/issues/14 but as the tool doesn't have an Energy Upgrade it seems like a different issue.

**Comment by KidsDontPlay** [comment]
which version?

**Comment by davqvist** [comment]
Oh my bad, I usually check for updates, but forgot this time. I updated to the newest version and now it works
