### ISSUE TITLE
Missing Sword Texture

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/Tools#4]
MC 1.12
Forge 2420
FT 1.2.1

Pretty much the title, the texture of the Sword is broken, is the default purple and black one.

**Comment by KidsDontPlay** [comment]
I can't reproduce that problem. Can you?

**Comment by davqvist** [comment]
Sure, happens in SP and MP. Modlist:
https://pastebin.com/1shVcupE

**Comment by KidsDontPlay** [comment]
maybe an incompatibility with another mod.
can you try it without any other mods installed?

**Comment by davqvist** [comment]
Works for me now, weird, I will reopen when I know more.

**Comment by FunnyMan3595** [comment]
This shows up in the Exoria modpack, and causes the sword to take on a texture from Advanced Rocketry.  I think the trigger on your end is `super(ToolHelper.newMat);` in ItemSword vs `super(name, ToolHelper.newMat, classes);` in GenericItemTool.  Providing the name to suoer() will likely restore the intended texture.

I'm not convinced that you're doing anything wrong, but it seems like a harmless enough change to make in the interests of compatibility.

**Comment by KidsDontPlay** [comment]
no.
you know nothing about java, do you?

**Comment by Invy55** [comment]
> no.
> you know nothing about java, do you?

This bug it's still in the mod...
