### ISSUE TITLE
[1.12] How do I charge tools?

### ISSUE THREAD

**Issue by Symbai** [KidsDontPlay/Tools#6]
It says "FU", what kind of energy is this? RE or FE with are used in very popular mods doesn't seem to work.

**Comment by KidsDontPlay** [comment]
These Tools support Redstone Flux, Forge Energy and Tesla.
I can charge them in AA Energizer and RFTools Powercell.
Have you installed Energy Upgrade?

**Comment by Symbai** [comment]
Yes I've installed the energy upgrade and it has 0 energy. Then I tried all kind of charge packs from Industrial Craft 2 that works absolutely fine with my Nano armor but the tools won't get charged.

**Comment by KidsDontPlay** [comment]
Are you kidding? 
I told you before that RF, FE and Tesla are supported. 
And you tried IC2 energy?
