### ISSUE TITLE
Range Upgrade interaction with IE Multiblocks

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/Tools#8]
MC 1.12
Forge 2443
FT 1.2.3

A FT 3x3 Pickaxe breaking an IE Coke Oven drops the whole multiblock instead of the block consisting in it. I assume other multiblocks cause the same issue.

**Comment by KidsDontPlay** [comment]
duplicate of #7
blusunrize will fix this.

**Comment by davqvist** [comment]
Oh sorry I didn't check closed issues, only open ones. thanks.
